name: CD Process
on:
  push:
    branches:
      - master
jobs:
  build-app:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Run Flutter Build
        run: flutter build appbundle
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: release
          path: build/app/outputs/apk/release
